name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. 0.1.0)"
        required: false
        type: string

jobs:
  publish-release:
    strategy:
      matrix:
        include:
          - os: macos-latest
            maker: dmg
          - os: windows-latest
            maker: squirrel
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v6

      - name: Install Node and NPM
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install and build
        working-directory: app
        run: npm ci

      - name: Make and Publish (${{ matrix.maker }})
        working-directory: app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
