/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthConnectWhatsappRouteImport } from './routes/auth/connect-whatsapp'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardConversationsIndexRouteImport } from './routes/dashboard/conversations/index'
import { Route as DashboardAppointmentsIndexRouteImport } from './routes/dashboard/appointments/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/dashboard/analytics/index'
import { Route as DashboardSettingsKnowledgeBaseRouteImport } from './routes/dashboard/settings/knowledge-base'
import { Route as DashboardCustomersIdRouteImport } from './routes/dashboard/customers/$id'
import { Route as DashboardConversationsIdRouteImport } from './routes/dashboard/conversations/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConnectWhatsappRoute = AuthConnectWhatsappRouteImport.update({
  id: '/auth/connect-whatsapp',
  path: '/auth/connect-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversationsIndexRoute =
  DashboardConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppointmentsIndexRoute =
  DashboardAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsKnowledgeBaseRoute =
  DashboardSettingsKnowledgeBaseRouteImport.update({
    id: '/settings/knowledge-base',
    path: '/settings/knowledge-base',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCustomersIdRoute = DashboardCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversationsIdRoute =
  DashboardConversationsIdRouteImport.update({
    id: '/conversations/$id',
    path: '/conversations/$id',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/connect-whatsapp': typeof AuthConnectWhatsappRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/dashboard/conversations/$id': typeof DashboardConversationsIdRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/settings/knowledge-base': typeof DashboardSettingsKnowledgeBaseRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/appointments/': typeof DashboardAppointmentsIndexRoute
  '/dashboard/conversations/': typeof DashboardConversationsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/connect-whatsapp': typeof AuthConnectWhatsappRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/dashboard/conversations/$id': typeof DashboardConversationsIdRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/settings/knowledge-base': typeof DashboardSettingsKnowledgeBaseRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/appointments': typeof DashboardAppointmentsIndexRoute
  '/dashboard/conversations': typeof DashboardConversationsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/connect-whatsapp': typeof AuthConnectWhatsappRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/dashboard/conversations/$id': typeof DashboardConversationsIdRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/settings/knowledge-base': typeof DashboardSettingsKnowledgeBaseRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/appointments/': typeof DashboardAppointmentsIndexRoute
  '/dashboard/conversations/': typeof DashboardConversationsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/connect-whatsapp'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/'
    | '/onboarding/'
    | '/dashboard/conversations/$id'
    | '/dashboard/customers/$id'
    | '/dashboard/settings/knowledge-base'
    | '/dashboard/analytics/'
    | '/dashboard/appointments/'
    | '/dashboard/conversations/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/connect-whatsapp'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/conversations/$id'
    | '/dashboard/customers/$id'
    | '/dashboard/settings/knowledge-base'
    | '/dashboard/analytics'
    | '/dashboard/appointments'
    | '/dashboard/conversations'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/connect-whatsapp'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/'
    | '/onboarding/'
    | '/dashboard/conversations/$id'
    | '/dashboard/customers/$id'
    | '/dashboard/settings/knowledge-base'
    | '/dashboard/analytics/'
    | '/dashboard/appointments/'
    | '/dashboard/conversations/'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthConnectWhatsappRoute: typeof AuthConnectWhatsappRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/connect-whatsapp': {
      id: '/auth/connect-whatsapp'
      path: '/auth/connect-whatsapp'
      fullPath: '/auth/connect-whatsapp'
      preLoaderRoute: typeof AuthConnectWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversations/': {
      id: '/dashboard/conversations/'
      path: '/conversations'
      fullPath: '/dashboard/conversations/'
      preLoaderRoute: typeof DashboardConversationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments/': {
      id: '/dashboard/appointments/'
      path: '/appointments'
      fullPath: '/dashboard/appointments/'
      preLoaderRoute: typeof DashboardAppointmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/knowledge-base': {
      id: '/dashboard/settings/knowledge-base'
      path: '/settings/knowledge-base'
      fullPath: '/dashboard/settings/knowledge-base'
      preLoaderRoute: typeof DashboardSettingsKnowledgeBaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers/$id': {
      id: '/dashboard/customers/$id'
      path: '/customers/$id'
      fullPath: '/dashboard/customers/$id'
      preLoaderRoute: typeof DashboardCustomersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversations/$id': {
      id: '/dashboard/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/dashboard/conversations/$id'
      preLoaderRoute: typeof DashboardConversationsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardConversationsIdRoute: typeof DashboardConversationsIdRoute
  DashboardCustomersIdRoute: typeof DashboardCustomersIdRoute
  DashboardSettingsKnowledgeBaseRoute: typeof DashboardSettingsKnowledgeBaseRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardAppointmentsIndexRoute: typeof DashboardAppointmentsIndexRoute
  DashboardConversationsIndexRoute: typeof DashboardConversationsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardConversationsIdRoute: DashboardConversationsIdRoute,
  DashboardCustomersIdRoute: DashboardCustomersIdRoute,
  DashboardSettingsKnowledgeBaseRoute: DashboardSettingsKnowledgeBaseRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardAppointmentsIndexRoute: DashboardAppointmentsIndexRoute,
  DashboardConversationsIndexRoute: DashboardConversationsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthConnectWhatsappRoute: AuthConnectWhatsappRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
